version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: unless-stopped


  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile.prod
    container_name: api-pharma-prod
    volumes:
      - ./api:/app/api
      - ./uploads:/app/uploads
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - db

  ml:
    build:
      context: .
      dockerfile: ./ml/Dockerfile.prod
    container_name: ml-prod
    ports:
      - "8100:8100"
    volumes:
      - ./ml:/app/ml
    env_file:
      - ./.env
    environment:
      - ARTIFACTS_DIR=/app/ml/artifacts
      - API_HOST=0.0.0.0
      - API_PORT=8100
      - MP_API_BASE=http://backend:8001
    depends_on:
      - backend

  tech_support:
    build:
      context: .
      dockerfile: ./tech_support/Dockerfile.prod
    container_name: tech-support-prod
    ports:
      - "8200:8200"
    volumes:
      - ./tech_support:/app/tech_support
    env_file:
      - ./.env
    environment:
      - TS_HOST=0.0.0.0
      - TS_PORT=8200
    depends_on:
      - backend


volumes:
  postgres-data: