version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: unless-stopped


  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile.prod
    container_name: api-pharma-prod
    volumes:
      - ./api:/app/api
      - ./uploads:/app/uploads
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - db


volumes:
  postgres-data: